openapi: 3.0.0
info:
  title: WASAText API
  description: |
    WASAText is a messaging platform that allows users to 
    communicate with contacts and groups.
  version: 0.0.1


servers:
  - url: http://localhost:3000


components:
  
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: |
        JWT access token using HS256.
        Standard claims:
        - **sub**: user ID (UUID)
        - **iat**: issued-at (unix timestamp)
        - **exp**: expiry timestamp
        - **iss**: "WASAText"


  headers:
    WWW-Authenticate:
      description: 'Authentication method required (Bearer).'
      schema:
        type: string
      example: 'Bearer realm="WASAText"'  

  schemas:

    Error:
      type: object
      properties:
        code:
          type: string
          example: "AUTH_FAILED"
        message:
          type: string
          example: "Missing or invalid access token."
        details:
          type: object
          nullable: true
      required:
        - code
        - message

    UserId:
      description: The unique identifier of a user.
      type: string
      format: uuid
      example: "123e4567-e89b-12d3-a456-426614174000"

    Username:
      description: The username of the user.
      type: string
      example: "johndoe"

    PhotoUrl:
      description: URL of the user's profile photo.
      type: string
      format: uri
      nullable: true
      example: "http://example.com/photos/johndoe.jpg"

    UserLoginRequest:
      description: Request payload for user login.
      type: object
      properties:
        username:
          $ref: '#/components/schemas/Username'
      required:
        - username

    UserLoginResponse:
      description: Response payload for user login.
      type: object
      properties:
        userId:
          $ref: '#/components/schemas/UserId'
        username:
          $ref: '#/components/schemas/Username'
        photoUrl:
          $ref: '#/components/schemas/PhotoUrl'

    AuthResponse:
      description: Authentication response including access token and user profile.
      type: object
      properties:
        accessToken:
          type: string
          description: Bearer access token (JWT or similar).
          example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
        tokenType:
          type: string
          example: "Bearer"
        expiresIn:
          type: integer
          description: Expiry in seconds.
          example: 3600
        issuedAt:
          type: string
          format: date-time
          example: "2025-11-16T12:00:00Z"
        expiresAt:
          type: string
          format: date-time
          example: "2025-11-16T13:00:00Z"
        isNewUser:
          type: boolean
          example: false
        user:
          $ref: '#/components/schemas/UserLoginResponse'
      required:
        - accessToken
        - tokenType
        - expiresIn
        - user


    ConversationId:
      description: The unique identifier of a conversation.
      type: string
      format: uuid
      example: "223e4567-e89b-12d3-a456-426614174001"

    MessageSnippet:
      description: A brief snippet of last message for each conversation.
      type: object
      properties:
        type: 
          type: string
          enum: [text, photo]
          example: "text"
        content:
          type: string
          example: "Hey, how are you?"
        timestamp:
          type: string
          format: date-time
          example: "2024-01-01T12:00:00Z"
      required:
        - type
        - content
        - timestamp

    ConversationSummary:
      description: Summary of a conversation.
      type: object
      properties:
        conversationId:
          $ref: '#/components/schemas/ConversationId'
        name:
          type: string
          example: "Frank Miller"
        photoUrl:
          $ref: '#/components/schemas/PhotoUrl'
        lastMessage:
          $ref: '#/components/schemas/MessageSnippet'
        lastActivity:
          type: string
          format: date-time
          example: "2024-01-01T12:00:00Z"
        isGroup:
          type: boolean
          example: false
        unreadCount:
          type: integer
          example: 2
      required:
        - conversationId
        - name
        - lastMessage
        - lastActivity

    MessageId: 
      description: The unique identifier of a message.
      type: string
      format: uuid
      example: "323e4567-e89b-12d3-a456-426614174002"

    MessageType:
      description: The type of message.
      type: string
      enum: [text, photo]
      example: "text"

    Message:
      description: A message in a conversation.
      type: object
      properties:
        messageId:
          $ref: '#/components/schemas/MessageId'
        conversationId:
          $ref: '#/components/schemas/ConversationId'
        senderId:
          $ref: '#/components/schemas/UserId'
        createdAt:
          type: string
          format: date-time
          example: "2024-01-01T12:00:00Z"
        type:
          $ref: '#/components/schemas/MessageType'
        content:
          description: The content of the message. This can be text or a URL to a photo depending on the message type.
          type: string
          example: "Hello!"
        deleted:
          type: boolean
          example: false
          nullable: true
        forwardedMessageId:
          $ref: '#/components/schemas/MessageId'
          nullable: true
        replyToMessageId:
          $ref: '#/components/schemas/MessageId'
          nullable: true
        editedAt:
          type: string
          format: date-time
          example: "2024-01-01T12:05:00Z"
          nullable: true
      required:
        - messageId
        - conversationId
        - senderId
        - createdAt
        - type
        - content

    MessageStatus:
      description: The status of a message for a user.
      type: object
      properties:
        messageId:
          $ref: '#/components/schemas/MessageId'
        recipientId:
          $ref: '#/components/schemas/UserId'
        deliveredAt:
          type: string
          format: date-time
          example: "2024-01-01T12:01:00Z"
          nullable: true
        readAt:
          type: string
          format: date-time
          example: "2024-01-01T12:03:00Z"
          nullable: true
      required:
        - messageId
        - recipientId

    ReactionId:
      description: The unique identifier of a reaction.
      type: string
      format: uuid
      example: "423e4567-e89b-12d3-a456-426614174003"
    
    Reaction:
      description: A reaction to a message.
      type: object
      properties:
        reactionId:
          $ref: '#/components/schemas/ReactionId'
        messageId:
          $ref: '#/components/schemas/MessageId'
        userId:
          $ref: '#/components/schemas/UserId'
        emoji:
          type: string
          example: "👍"
        reactedAt:
          type: string
          format: date-time
          example: "2024-01-01T12:02:00Z"
      required:
        - reactionId
        - messageId
        - userId
        - emoji
        - reactedAt

  responses:
    Unauthorized:
      description: Unauthorized - missing or invalid token.
      headers:
        WWW-Authenticate:
          $ref: '#/components/headers/WWW-Authenticate'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            missing_token:
              summary: Missing access token
              value:
                code: "AUTH_MISSING_TOKEN"
                message: "Missing access token."
                details: null

    Forbidden:
      description: Forbidden - authenticated but not allowed to access this resource.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            not_allowed:
              summary: Access forbidden
              value:
                code: "AUTH_FORBIDDEN"
                message: "You do not have permission to access this resource."
                details: null

    BadRequest:
      description: Bad Request - invalid input.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            invalid_input:
              summary: Invalid input data
              value:
                code: "INVALID_INPUT"
                message: "The provided input data is invalid."
                details:
                  field_errors:
                    username: "Username must be at least 3 characters long."

    Conflict:
      description: Conflict - username not allowed or other business conflict.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            resource_already_exists:
              summary: Resource already exists
              value:
                code: "RESOURCE_CONFLICT"
                message: "The username is already taken."
                details: null

    TooManyRequests:
      description: Too Many Requests - rate limit exceeded.
      headers:
        Retry-After:
          description: Seconds to wait before retrying.
          schema:
            type: string
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            rate_limit_exceeded:
              summary: Rate limit exceeded
              value:
                code: "RATE_LIMIT_EXCEEDED"
                message: "You have exceeded the number of allowed requests. Please try again later."
                details: null

    InternalError:
      description: Internal Server Error.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            internal_server_error:
              summary: Internal server error
              value:
                code: "INTERNAL_SERVER_ERROR"
                message: "An unexpected error occurred. Please try again later."
                details: null


security:
  - bearerAuth: []

paths:
  /auth/login:
    post:
      security: []
      summary: User Login
      description: Authenticates a user and returns their user ID, username, and profile photo URL.
      operationId: doLogin
      requestBody:
        description: User login request payload.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLoginRequest'
      responses:
        '200':
          description: Successful login.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthResponse"
        '400':
          $ref: '#/components/responses/BadRequest'
        '409':
          $ref: '#/components/responses/Conflict'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalError'
  
  /conversations:
    get:
      summary: Get my conversations
      description: Returns the authenticated user's conversation list in reverse chronological order.
      operationId: getMyConversations
      parameters:
        - name: cursor
          in: query
          description: Opaque cursor for pagination (fetch items before this cursor).
          required: false
          schema:
            type: string
        - name: limit
          in: query
          description: Maximum number of items to return.
          required: false
          schema:
            type: integer
            format: int32
            default: 20
      responses:
        '200':
          description: A list of conversation summaries.
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/ConversationSummary'
                  nextCursor:
                    type: string
                    nullable: true
                required:
                  - items
                  - nextCursor
              examples:
                sample_response:
                  summary: Response with conversation summaries
                  value:
                    items:
                      - conversationId: "223e4567-e89b-12d3-a456-426614174001"
                        name: "Frank Miller"
                        photoUrl: "http://example.com/photos/frank.jpg"
                        lastMessage:
                          type: "text"
                          content: "Hey, how are you?"
                          timestamp: "2024-01-01T12:00:00Z"
                        lastActivity: "2024-01-01T12:00:00Z"
                        isGroup: false
                        unreadCount: 2
                    nextCursor: "opaque-cursor-string"
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
