openapi: 3.0.0
info:
  title: WASAText API
  description: |
    WASAText is a PC based messaging platform that allows 
    users to communicate with contacts and groups.

  version: 0.0.1

servers:
  - url: http://localhost:3000

components:

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: |
        JWT access token using HS256.
        Standard claims:
        - **sub**: user ID (UUID)
        - **iat**: issued-at (unix timestamp)
        - **exp**: expiry timestamp
        - **iss**: "WASAText"

  headers:
    WWW-Authenticate:
      description: 'Authentication method required (Bearer).'
      schema:
        type: string
      example: 'Bearer realm="WASAText"'  

  schemas:

    Error:
      type: object
      properties:
        code:
          type: string
          example: "AUTH_FAILED"
        message:
          type: string
          example: "Missing or invalid access token."
        details:
          type: object    
      required:
        - code
        - message

    UserId:
      description: The unique identifier of a user.
      type: string
      format: uuid
      example: "123e4567-e89b-12d3-a456-426614174000"

    Username:
      description: The username of the user.
      type: string
      example: "johndoe"

    PhotoUrl:
      description: URL of the user's profile photo.
      type: string
      format: uri
      example: "http://example.com/photos/johndoe.jpg"

    UserInfo:
      description: Response payload for user login.
      type: object
      properties:
        userId:
          $ref: '#/components/schemas/UserId'
        username:
          $ref: '#/components/schemas/Username'
        photoUrl:
          $ref: '#/components/schemas/PhotoUrl'

    AuthResponse:
      description: Authentication response including access token and user profile.
      type: object
      properties:
        accessToken:
          type: string
          description: |
            JWT access token encoded using HS256.
            Send it in the header: `Authorization: Bearer <accessToken>`.
            Typical claims included:
            - sub: user ID (UUID)
            - iat: issued-at timestamp
            - exp: expiration timestamp
            - iss: "WASAText"
          example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
        tokenType:
          type: string
          example: "Bearer"
        expiresIn:
          type: integer
          description: Expiry in seconds.
          example: 3600
        issuedAt:
          type: string
          format: date-time
          example: "2025-11-16T12:00:00Z"
        expiresAt:
          type: string
          format: date-time
          example: "2025-11-16T13:00:00Z"
        isNewUser:
          type: boolean
          example: false
        user:
          $ref: '#/components/schemas/UserInfo'
      required:
        - accessToken
        - tokenType
        - expiresIn
        - user

    ConversationId:
      description: The unique identifier of a conversation.
      type: string
      format: uuid
      example: "223e4567-e89b-12d3-a456-426614174001"

    MessageType:
      type: string
      enum: [text, photo, text_with_photo]
      example: "text_with_photo"

    MessageContent:
      type: object
      properties:
        text:
          type: string
        photoUrl:
          $ref: '#/components/schemas/PhotoUrl'

    MessageSnippet:
      description: A brief snippet of the last message for each conversation.
      type: object
      properties:
        messageId:
          $ref: "#/components/schemas/MessageId"
        contentPreview:
          type: string
          maxLength: 50
          example: "Hey, how are you?"
      required:
        - messageId
        - contentPreview
      # si potrebbe sostituire con [messageId, contentPreview]

    ConversationSummary:
      type: object
      properties:
        conversationId:
          $ref: '#/components/schemas/ConversationId'
        name:
          type: string
        photoUrl:
          $ref: '#/components/schemas/PhotoUrl'
          nullable: true
        lastMessage:
          $ref: '#/components/schemas/MessageSnippet'
        lastActivity:
          type: string
          format: date-time
        isGroup:
          type: boolean
          default: false
        unreadCount:
          type: integer
          default: 0
      required:
        - conversationId
        - name
        - lastMessage
        - lastActivity


    MessageId: 
      description: The unique identifier of a message.
      type: string
      format: uuid
      example: "323e4567-e89b-12d3-a456-426614174002"

    
    Message:
      description: A message in a conversation.
      type: object
      properties:
        messageId: # deve essere diverso da forwardedMessageId e replyToMessageId
          $ref: '#/components/schemas/MessageId' 
        conversationId:
          $ref: '#/components/schemas/ConversationId'
        senderId:
          $ref: '#/components/schemas/UserId'
        createdAt:
          type: string
          format: date-time
          example: "2024-01-01T12:00:00Z"
        type:
          $ref: '#/components/schemas/MessageType'
        content:
          $ref: '#/components/schemas/MessageContent'
        deleted:
          type: boolean
          example: false
        forwardedMessageId:
          $ref: '#/components/schemas/MessageId'
        replyToMessageId:
          $ref: '#/components/schemas/MessageId'
        editedAt: # vediamo se serve implementare questa funzionalità
          type: string
          format: date-time
          example: "2024-01-01T12:05:00Z"  
      required:
        - messageId
        - conversationId
        - senderId
        - createdAt
        - type
        - content

    MessageStatus:
      description: The status of a message for a user.
      type: object
      properties:
        messageId:
          $ref: '#/components/schemas/MessageId'
        recipientIds:
          type: array
          items: 
            $ref: '#/components/schemas/UserId'
          minItems: 1
        readAt: # orario in cui l'ultimo dei riceventi ha letto il messaggio, se nullo significa che almeno 1 ricevente non l'ha letto
          type: string
          format: date-time
          example: "2024-01-01T12:03:00Z"    
      required:
        - messageId
        - recipientIds

    ReactionId:
      description: The unique identifier of a reaction.
      type: string
      format: uuid
      example: "423e4567-e89b-12d3-a456-426614174003"
    
    Reaction:
      description: A reaction to a message.
      type: object
      properties:
        reactionId:
          $ref: '#/components/schemas/ReactionId'
        messageId:
          $ref: '#/components/schemas/MessageId'
        userId:
          $ref: '#/components/schemas/UserId'
        emoji:
          type: string
          example: "👍"
        reactedAt:
          type: string
          format: date-time
          example: "2024-01-01T12:02:00Z"
      required:
        - reactionId
        - messageId
        - userId
        - emoji
        - reactedAt

  responses:
    Unauthorized:
      description: Unauthorized - missing or invalid token.
      headers:
        WWW-Authenticate:
          $ref: '#/components/headers/WWW-Authenticate'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            missing_token:
              summary: Missing access token
              value:
                code: "AUTH_MISSING_TOKEN"
                message: "Missing access token."
                details: null
    
    Forbidden:
      description: Forbidden - authenticated but not allowed to access this resource.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            not_allowed:
              summary: Access forbidden
              value:
                code: "AUTH_FORBIDDEN"
                message: "You do not have permission to access this resource."
                details: null

    BadRequest:
      description: Bad Request - invalid input.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            invalid_input:
              summary: Invalid input data
              value:
                code: "INVALID_INPUT"
                message: "The provided input data is invalid."
                details:
                  field_errors:
                    username: "Username must be at least 3 characters long."

    Conflict:
      description: Conflict - username not allowed or other business conflict.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            resource_already_exists:
              summary: Resource already exists
              value:
                code: "RESOURCE_CONFLICT"
                message: "The username is already taken."
                details: null

    TooManyRequests:
      description: Too Many Requests - rate limit exceeded.
      headers:
        Retry-After:
          description: Seconds to wait before retrying.
          schema:
            type: string
          example: "60"
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            rate_limit_exceeded:
              summary: Rate limit exceeded
              value:
                code: "RATE_LIMIT_EXCEEDED"
                message: "You have exceeded the number of allowed requests. Please try again later."
                details: null

    InternalError:
      description: Internal Server Error.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            internal_server_error:
              summary: Internal server error
              value:
                code: "INTERNAL_SERVER_ERROR"
                message: "An unexpected error occurred. Please try again later."
                details: null

security:
  - bearerAuth: []

paths:
  /auth/login:
    post:
      security: []
      summary: User Login
      description: Authenticates a user and returns their user ID, username, and profile photo URL.
      operationId: doLogin
      requestBody:
        description: User login request payload.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Username"
      responses:
        '200':
          description: Successful login.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthResponse"
        '201':
          description: New user created and logged in.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthResponse"
        '400':
          $ref: '#/components/responses/BadRequest'
        '409':
          $ref: '#/components/responses/Conflict'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalError'

  /me/username:
    patch:
      summary: Sets my username
      description: Sets the authenticated user's username.
      operationId: setMyUserName
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Username"
      responses:
        '200':
          description: Username set successfully.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserInfo"
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '409':
          $ref: '#/components/responses/Conflict'
        '500':
          $ref: '#/components/responses/InternalError'

  /me/photo:
    patch:
      summary: Sets my profile photo URL
      description: Sets the authenticated user's profile photo URL.
      operationId: setMyPhoto
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PhotoUrl"
      responses:
        '200':
          description: Profile photo URL set successfully.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserInfo"
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/InternalError'